# Generated by Django 4.2 on 2025-04-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], default='Gasto', max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(),
        ),
    ]
