# Generated by Django 4.2 on 2025-04-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0002_prestamo_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Movimientos.prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
