# Generated by Django 4.2 on 2025-04-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0002_categoria_tipo_alter_registro_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
