# Generated by Django 4.2 on 2025-04-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0003_registro_prestamo_alter_prestamo_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='estado',
        ),
    ]
