# Generated by Django 4.2 on 2025-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0003_rename_descipcion_registro_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
