# Generated by Django 4.2 on 2025-04-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0004_remove_registro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='estado',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.estado'),
        ),
    ]
