# Generated by Django 4.2 on 2025-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0005_registro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='detalle',
            field=models.CharField(default='Sin detalle', max_length=200),
            preserve_default=False,
        ),
    ]
