# Generated by Django 4.2 on 2025-04-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0008_categoria_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='descripcion',
            new_name='detalle',
        )
    ]
