# Generated by Django 4.2 on 2025-04-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0009_auto_20250420_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acreedor',
            new_name='Persona',
        )
    ]
