# Generated by Django 4.2 on 2025-04-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0010_auto_20250420_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de movimiento', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='acreedor',
            new_name='persona',
        ),
        migrations.AddField(
            model_name='registro',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Movimientos.persona'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.categoria'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='detalle',
            field=models.CharField(db_column='descripcion', help_text='Descripción del movimiento', max_length=200),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.estado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(help_text='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='prestamo',
            field=models.BooleanField(default=False, help_text='¿Es un prestamo?', verbose_name='¿Es un prestamo?'),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.tipo'),
        ),
    ]
