# Generated by Django 4.2 on 2025-04-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0012_alter_registro_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='persona',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
