# Generated by Django 4.2 on 2025-05-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0014_pagoprestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoprestamo',
            name='prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='saldo',
        ),
        migrations.AddField(
            model_name='pagoprestamo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.persona'),
        ),
    ]
